name: AI QA Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  ai-testing:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps


      - name: Run RCA Agent
        run: node rca-test.js

      - name: Generate Dashboard Report
        run: node generate-dashboard-report.js

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: ai-qa-reports
          path: |
            *.json
            *.png
            qa-dashboard/public/screenshots/
